project:
  type: website

website:
  title: "OJJDP Juvenile Justice System Reform Initiative: Virginia"
  favicon: img/favicon.png
  navbar:
   right:
      - text: "Project and Analysis Plan"
        href: index.html
      - text: "Part I Analysis"
        menu:
          - text: "Descriptive Overview"
            href: ojjdp_va_part_i_analysis_overview.html
          - text: "Regression Analysis"
            href: ojjdp_va_part_ii_analysis_regression.html
      - text: "Part II Analysis"
        menu:
          - text: "Diversion Trends"
            href: ojjdp_va_part_ii_analysis_diversion.html
          - text: "Disposition Trends"
            href: ojjdp_va_part_ii_analysis_dispo.html
          - text: "Race/Ethnicity"
            href: ojjdp_va_part_ii_analysis_race_ethnicity.html
      - text: "Questions and Updates"
        href: ojjdp_va_questions_updates.html
      - text: "Analytic File Prep"
        href: ojjdp_va_create_analytic_files.html
      - text: "Sample Descriptives"
        menu:
          - text: "Basic Descriptive Statistics"
            href: ojjdp_va_preliminary_descriptives.html
          - text: "Codebooks"
            href: ojjdp_va_data_codebooks.html
          - text: "Data Diagram"
            href: ojjdp_va_data_diagram_viz.html
      - icon: fab fa-github
        href: https://github.com/CSGJusticeCenter/jj_ojjdp_va

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left

execute:
  freeze: auto