---
title: "Virginia DJJ Data Questions/Updates"
format: html
---


**Virginia DJJ Data Questions and Responses:**

*Questions about the disposition file:*

*	The disposition file appears to have a small number of pure duplicates (~850/~370,000) and a somewhat larger population of duplicates across youth ID, case number, offense, and disposition (~11,000/~370,000). How should we interpret/treat this? It seems like one case could have multiple intakes and thus, multiple measures of days from intake to disposition -- but for one offense ID

*Response from Nina: One case can have multiple complaints (aka offenses) and each one of the offenses may have one or more dispositions. So yes, there can be multiple measures of days from intake to disposition. The field in our data system calls it the court ordered date since the word “disposition” can mean different things to different individuals. Follow up from phone call: I looked at the data in our data system and the duplicates are correct. For example, the youth may be given more than one type of court ordered condition and the PO may put a disposition for each specific type.*


*	We seem to be missing description, days_int_to_cd, and court_disp_age for about half of the records in the file. Are these intake complaints without dispositions? Or how should we interpret this?

*Response from Nina: Since the complaint is diverted the worker may not have entered a disposition. The disposition and intake decision are captured in two different fields.*


*Questions about the intake complaints file:*

Missing data:

*	How should we interpret missing prior JJ complaint data? About 40% of all intake complaints records appear to have missing data in these columns

*Response from Nina: Missing means the youth had no prior involvement across all offense types/severities. For the records that have 0 rather than blank, this means they had no type of prior for that field (for example, if prior felony is 0 it means they had no prior felonies). However, they youth may have had a different type of prior (based on the example, the youth may have had a prior misdemeanor).*


*	We seem to be missing age (pet_age) for about 35% of all records in the intake complaints file -- how should we interpret this? 

*Response from Nina: Not all complaints are petitioned. If the case is not petitioned the age will be missing. The percentage missing decreases to less than one percent when intake decision is taken into consideration.*


*	It also appears that we have risk level, mental health flag, and other assessment information for only about 38% of all records in the intake complaints file.

*Response from Nina: Not every youth gets a YASI at intake. The youth will usually get a YASI if they have a social history completed, if they are placed on probation, or if they are committed.*


*	Should we use intake decision to create the diverted versus not diverted samples? Are these codes overwritten over time?	If so, which intake decision codes belong in the diverted group ("UNSUCCESSFUL DIVERSION/PETITION FILED" (code of '18'), "SUCCESSFUL DIVERSION" (code of '20'), and "UNSUCCESSFUL DIVERSION/NO PETITION FILED" (code of '21'),"REQ'D TO PARTICIPATE-DIVERSION" (code of '7')?)

*Response from Nina: The only codes that are overwritten are the diversion intake decisions. ),"REQ'D TO PARTICIPATE-DIVERSION" means the youth has an open diversion plan. When the diversion plan is closed they are either changed to one of the unsuccessful codes or the successful code. You can see how we categorize the different intake decisions on page 18 of the Data Resource Guide, FY 2022.*


*New Questions* 

* Could you walk us through the difference between CHINS, CHINSUP, and STATUS categories? Why are all three categories (CHINS, CHINSUP, STATUS) included in prior history, but only status included in current charge? 

*Response from Nina:* 

*These definitions are from pages 4, 5, and 96 of the Data Resource Guide, FY 2022.* 

*-	CHINS: a child whose behavior, conduct, or condition presents or results in a serious threat to (i) the wellbeing and physical safety of that child or, (ii) if under the age of 14, the well-being and physical safety of another person. To meet the definition of CHINS, there must be a clear and substantial danger to the life or health of the child or another person, and the intervention of the court must be found to be essential to provide the treatment, rehabilitation, or services needed by the child or the child’s family. See § 16.1-228 of the Code of Virginia.*
*-	CHINSup: a child who (i) is habitually and without justification absent from school despite opportunity and reasonable effort to maintain school attendance, (ii) runs away from family or lawful custodian on more than one occasion, or (iii) escapes from or leaves a court-ordered residential placement without permission. See § 16.1-228 of the Code of Virginia.*

*In the file the Prior Other Status includes the following:*
*-	Other Status Offenses: In the appendix of the DRG you can find the offenses that are considered other status offenses. See below.*
 
*-	Marijuana Status: As of FY 2022, the “Narcotics” offense category no longer includes marijuana possession offenses. These offenses are captured under the new VCC prefix, MRJ. Beginning in FY 2022, there are two “Marijuana” categories: delinquent marijuana offenses and status marijuana offenses.*



* How should we interpret FIPS codes of X71 and X21 (both associated with CSU 029)?

*Response from Nina: X indicates that the code was expired. In this case both FIPS were part of CSU 29. Effective in FY 2019, Bland Co. (FIPS 021) and Giles Co. (FIPS 071) are part of CSU 27. *


* Should we be using the Offense Type column or Delinquent/Status/Technical/Traffic flag to select complaints that are status-related? Or does it not matter?

*Response from Nina: This is something that was included with the request. I believe it was categorized the same way the offenses are categorized on page 21 of the Data Resource Guide, FY 2022.*


* Do you all have a rule for excluding youth of certain ages from analysis (based on the assumption that it is likely a data entry error? e.g., ages of 0-4 or 25+?) Or are the ages accurate and reflect non-JJ involvement?

*Response from Nina: I think it depends on the type of offense/ages. I would exclude “youth” 21 and over since those are most likely data entry errors. Depending on the offense category, the younger ages (0-4 years) may be accurate. For example, if it’s a CHINS complaint the child may actually be 0-4 years old. For the rest of the complaints it is most likely a data entry error. For the Data Resource Guide, our cut off for the intake section is 8 to 20 years old.*



*Questions about the caseload file:*

*	Caseload file seems to have duplicates across youth ID (juvenile number) and offense number -- how should we interpret this?

*Response from Nina: The worker selects a caseload status and then associates one or more offenses with it. The youth’s status can change, for example, the youth may be placed on diversion and then abscond and then go back on diversion status. In this scenario, the  youth would have two diversion statuses in the file since it counts the LOS for each status individually.*


*	What is the best way to join the caseload file to the other files (without case number)?

*Response from Nina: I would use the juvenile number and offense number both are unique to youth. The same offense number is not used for other youth who had the same offense.*


*	We seem to be missing div_at_int and div_bey_90 for the vast majority of the records in the file (87%+). Are these intake complaints that were not diverted? Or how should we interpret this? 

*Response from Nina: It looks like if the offense(s) were not associated with a diversion caseload status and that is why it is blank. They may have a different workload status(es). For example, you can see the probation and parole workload statuses on page 97 of the DRG. Data entry practices for diversion caseload statuses may vary by CSU.*

*- Update since our call: I verified with the person that wrote the query. If the youth has the juvenile number and offense number filled in but the two diversion columns are blank. It means the youth had another type of caseload status (pre-Dispositional tracking, probation, parole, etc.) or they did not have any caseload statuses. So it is possible to have the number of days for the two diversion codes filled in and also have a blank row because they had another type of status. If we have to rerun the data we can change the rules to exclude the blanks.*


* Do youth get a YASI when they are diverted? 

*Response from Nina: It is not in the procedure but in practice it may vary. I would defer to Ms. McWilliams on the answer to this question.* 


*	Are the prior fields mutually exclusive? 

*Response from Nina: Certain fields will not overlap (e.g., prior felony and prior misdemeanor). The only field that may overlap with felony and misdemeanor is the “other status” category. Different reference tables are used to calculate these fields. There should not be a huge overlap but it is possible. We could probably add a field for the total number of priors (let me know if you want any exclusions) because that shouldn’t change the scope of the project/ what you already requested.* 



<br>

**Current Internal Questions & Next Steps:**

- We have CHINS/CHINSup/status split out for history, but not current charge

- Language: complaint vs intake complaint vs intake case

- For complaint-level analysis, I've created a unique complaint ID using juvenile_number and case_number

- Other variables to categorize/group: `intake decision` (see table 3 on basic descriptives page), `petitioner type` (see table 4 on basic descriptives page), `disposition type` (see table 8 on basic descriptives page), `offense description` for status offenses (see table 7 on basic descriptives page)

- Do we want to include the following intake decisions/types in our base sample: "COMPLAINT UNFOUNDED", "SHELTER CARE ONLY", "RETURNED TO OUT-OF-STATE", "REFERRED TO ANOTHER AGY FOR SV", "RESOLVED", "PENDING"? Look at DJJ-provided descriptions for these, as well.

- Do we want to explore both CSU-level and region-level variation? (see: https://www.djj.virginia.gov/pages/community/court-service-units.htm)

<br>
