---
title: "Building the Analytic Files"
format: html
---

In this syntax, we'll import all of the DJJ files provided and create two analytic files based on the templates in the second and third tabs here: https://csgorg.sharepoint.com/:x:/s/Team-JC-Research-JJ_AV/EZ-RDTetlZVCoiQxlasiboEBhsT7WNlx5v0qR7sDBji1-A?e=eggzRJ

See `Codebooks` and `Data Diagram` tabs for more information on each individual data file. 

```{r include=FALSE}
### call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap", "raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","csgjcr","DataExplorer","tidylog")
```

```{r }
### pull in virginia djj data from raw data folder

### set sharepoint path using csgjcr function
sharepoint_ojjdp_va_raw_data <- csgjcr::csg_sp_path(file.path("JJ_OJJDP/Data/VA/raw"))

### set sharepoint path using csgjcr function
sharepoint_ojjdp_va_viz <- csgjcr::csg_sp_path(file.path("JJ_OJJDP/Output/VA/r_viz_output"))

########################################################
### import first excel file w/ multiple tabs with purrr
########################################################

### using purrr::map, import list of tabs from excel worksheet
ojjdp_va_raw_tab_list_file_one <- purrr::map(purrr::set_names(excel_sheets(file.path(sharepoint_ojjdp_va_raw_data,
                                                              "CSG Front End data 01202023 - pt1 - SENSITIVE.xlsx"))),
                      read_excel, 
                      path = file.path(sharepoint_ojjdp_va_raw_data,"CSG Front End data 01202023 - pt1 - SENSITIVE.xlsx")) %>% 
  purrr::map(janitor::clean_names)

### clean names of all imported tabs before converting to dataframes
names(ojjdp_va_raw_tab_list_file_one) <- janitor::make_clean_names(names(ojjdp_va_raw_tab_list_file_one))

### then convert list of tabs to distinct dataframes with names from tabs
purrr::map(names(ojjdp_va_raw_tab_list_file_one),
           ~assign(.x, 
                   ojjdp_va_raw_tab_list_file_one[[.x]], 
        envir = .GlobalEnv)) 

########################################################
### now import second file from djj -- with only one tab
########################################################
df_djj_intake_complaints_raw <- openxlsx::read.xlsx(file.path(sharepoint_ojjdp_va_raw_data,
                                                              "CSG Front End data 01202023 - pt2 - SENSITIVE.xlsx"),
                                                    sheet = 1) %>% 
  clean_names()
```

```{r }
### create lists of court service unit (CSU) regions
### see here: https://www.djj.virginia.gov/pages/community/court-service-units.htm
eastern_region <- c("001",
                    "002",
                    "02A",
                    "003",
                    "004",
                    "005",
                    "007",
                    "008")

northern_region <- c("017",
                    "018",
                    "019",
                    "020",
                    "026",
                    "031")

western_region <- c("021",
                    "022",
                    "023",
                    "027",
                    "028",
                    "029",
                    "030")

southern_region <- c("006",
                    "010",
                    "011",
                    "012",
                    "013",
                    "014")

central_region <- c("009",
                    "015",
                    "016",
                    "024",
                    "013",
                    "025")
```

```{r }
#####################################
### first explore how mso_flag (which flags most serious offense per case) is created b/c this is 
### how we will de-dup the complaints file and DJJ noted that one case may have two offenses flagged as "Yes" with the mso_flag if the severity rankings tie
### looking at the df produced here, the severity hierarchy appears to be created using vcc code (The Virginia Crime Code of the offense) 
### so by de-duping using mso_flag, we won't lose any offense-level data
### since we are calculating case-level counts of offenses by each category, this de-duping strategy 
### seems good to go
######################################################################################################
df_djj_intake_complaints_raw_mso_flag_dups_explore <- df_djj_intake_complaints_raw %>% 
  dplyr::filter(mso_flag == "Y") %>% 
  group_by(juvenile_number,
           case_number,
           mso_flag) %>% 
  mutate(sequence = row_number(),
         dup_mso=n()>1) %>% 
  ungroup() %>% 
  filter(dup_mso==TRUE) %>% 
  dplyr::select(juvenile_number,
           case_number,
           offense_number,
           mso_flag,
           dup_mso,
           sequence,
           vcc_code,
           description,
           dai,
           flg_category)


########################################
### clean and de-dup caseload dataframe
### we will then join this file to the intake complaints file, before we de-dup the intake complaints file by case/complaint. b/c the caseload file only contains youth ID and offense ID as unique identifiers, we need to join to intake complaints when the full universe of offense IDs is still present
### we'll then group by case/complaint to create LOS measures, from caseload, for our analysis
### first, here is some caseload-specific cleaning we need to do
########################################

###############################################
### from Nina on missing values:

### "I verified with the person that wrote the query. If the youth has the juvenile number and offense number filled in but the two diversion columns are blank. It means the youth had another type of caseload status (pre-Dispositional tracking, probation, parole, etc.) or they did not have any caseload statuses. So it is possible to have the number of days for the two diversion codes filled in and also have a blank row because they had another type of status. If we have to rerun the data we can change the rules to exclude the blanks."

### BUSINESS RULE: based on this, I am dropping records with missing values for either div_at_int or div_bey_90
################################################

################################################
### from Nina on duplicate youth and offense IDs

### "The worker selects a caseload status and then associates one or more offenses with it. The youth’s status can change, for example, the youth may be placed on diversion and then abscond and then go back on diversion status. In this scenario, the  youth would have two diversion statuses in the file since it counts the LOS for each status individually."

### BUSINESS RULE: based on this, i think it's best to group by youth ID and offense ID, add up all LOS values, and then de-duplicate
#################################################

caseload_clean <- caseload %>% 
  filter(!is.na(div_at_int) | !is.na(div_bey_90)) %>% 
  mutate(div_at_int = as.numeric(div_at_int),
         div_bey_90 = as.numeric(div_bey_90)) %>% 
  group_by(juvenile_number,
           offense_number) %>% 
  mutate(div_at_int = sum(div_at_int, na.rm = TRUE),
         div_bey_90 = sum(div_bey_90, na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(juvenile_number,
           offense_number,
           .keep_all=TRUE) 

#############################################
### clean and de-dup df_djj_intake_complaints_raw dataframe by complaint/case (keeping most serious offense)
### this is our base complaint/offense-level file for the sample
#############################################
df_djj_intake_complaints_clean <- df_djj_intake_complaints_raw %>% 
  distinct(juvenile_number,
           case_number,
           offense_number,
           .keep_all=TRUE) %>% ### no records dropped
  ### we need to join caseload_clean to the intake complaints file before we de-dup the intake complaints file by case/complaint (keeping most serious offense). b/c the caseload file only contains youth ID and offense ID as unique identifiers, we need to join to intake complaints when the full universe of offense IDs is still present
  ### we'll then group by case/complaint to create LOS measures, from caseload, for our analysis
    left_join(caseload_clean,
            by = c("juvenile_number",
                   "offense_number")) %>% 
  ### create counts vars by charge category before de-duping with mso_flag (keeping the most serious offense)
  group_by(juvenile_number,
           case_number) %>% 
  mutate(count_felony_with_case = n_distinct(offense_number[dai%in%c("Felony against Persons",
                                                                     "Felony Weapons and Felony Narcotics Distribution",
                                                                     "Other Felony")]),
         count_misd_with_case = n_distinct(offense_number[dai%in%c("Class 1 Misdemeanor Against Persons",
                                                                     "Other Class 1 Misdemeanor")]),
         count_status_with_case = n_distinct(offense_number[dai%in%c("Status Offense")]),
         count_violation_with_case = n_distinct(offense_number[dai%in%c("Other Violation",
                                                                        "Court Order Violation",
                                                                        "Prob./Parole Violation")]),
         div_at_int = sum(div_at_int, na.rm = TRUE),
         div_bey_90 = sum(div_bey_90, na.rm = TRUE)) %>%
  ungroup() %>% 
  ### keep most serious offense associated with intake case/complaint
  dplyr::filter(mso_flag == "Y") %>% 
  ### according to DJJ documentation, multiple offenses may have mso flag of 1 if
  ### severity ranking is tied; it appears that ties only occur with identical vcc codes
  ### but will confirm with Nina
  distinct(juvenile_number,
           case_number,
           .keep_all=TRUE) %>% 
  ### clean race/ethnicity and gender
  ### use factor function to assign labels to values
  mutate(race_clean = case_when(
    race=="I" & hispanic!="Y" ~ 1,
    race=="A" & hispanic!="Y" ~ 2,
    race=="B" & hispanic!="Y" ~ 3,
    hispanic=="Y" ~ 4,
    race=="W" & hispanic!="Y" ~ 5,
    race %in% c("X","O") & hispanic!="Y" ~ 6,
    TRUE ~ as.numeric(NA)),
    race_clean = factor(race_clean,
         levels = c(1,2,3,4,5,6),
         labels = c("American Indian","Asian", "Black", "Hispanic", "White", "Other"))) %>% 
  mutate(gender_clean = case_when(
    sex=="F" ~ 1,
    sex=="M" ~ 2,
    TRUE ~ as.numeric(NA)),
    gender_clean = factor(gender_clean,
         levels = c(1,2),
         labels = c("Female", "Male"))) %>% 
  ### temp cleaning of age -- pending feedback from DJJ
  mutate(petition_age_clean = case_when(
    pet_age < 12 ~ 1,
    pet_age>= 12 &  pet_age< 14 ~ 2,
    pet_age>= 14 &  pet_age< 16 ~ 3,
    pet_age>= 16 &  pet_age< 20 ~ 4,
    TRUE ~ as.numeric(NA)),
    petition_age_clean = factor(petition_age_clean,
         levels = c(1,2,3,4),
         labels = c("Less than 12", 
                    "12 to 13",
                    "14 to 15",
                    "16 to 20")),
    intake_age_clean = case_when(
    intake_age < 12 ~ 1,
    intake_age>= 12 &  intake_age< 14 ~ 2,
    intake_age>= 14 &  intake_age< 16 ~ 3,
    intake_age>= 16 &  intake_age< 20 ~ 4,
    TRUE ~ as.numeric(NA)),
    intake_age_clean = factor(intake_age_clean,
         levels = c(1,2,3,4),
         labels = c("Less than 12", 
                    "12 to 13",
                    "14 to 15",
                    "16 to 20")),
    risk_level_clean = case_when(
    risk_level=="L" ~ 1,
    risk_level=="M" ~ 2,
    risk_level=="H" ~ 3,
    TRUE ~ as.numeric(NA)),
    risk_level_clean = factor(risk_level_clean,
         levels = c(1,2,3),
         labels = c("Low", 
                    "Medium",
                    "High"))) %>%   
  ### clean dates and create year for potential grouping in future trend analysis
  mutate(date_opened = ymd(as_date(excel_numeric_to_date(as.numeric(as.character(date_opened)), 
                                                  date_system = "modern"))),
         ysai_date = ymd(as_date(ysai_date)),
         date_opened_year = year(date_opened)) %>% 
  ### remove records for youth/individuals younger than 8 and older than 20
  ### feedback from Nina on this business rule: 
  ### "I would exclude “youth” 21 and over since those are most likely data entry errors. 
  ### Depending on the offense category, the younger ages (0-4 years) may be accurate. 
  ### For example, if it’s a CHINS complaint the child may actually be 0-4 years old. 
  ### For the rest of the complaints it is most likely a data entry error. For the Data Resource Guide, 
  ### our cut off for the intake section is 8 to 20 years old
  filter((drg=="CHINS" | intake_age >=8),
         intake_age<=20)

### clean up codebook values that we need
codebook_intake_decision_values <- codebook %>% 
  filter(field_name=="INTAKE_DECISION") %>% 
  dplyr::select(intake_decision=code,
                intake_decision_label=options,
                intake_decision_description=definitions) %>% 
  mutate(intake_decision = as.numeric(intake_decision))

### categorize intake decisions, referral source, and jj history
### join in lookup values from DJJ-provided codebook
df_complaints_youth_intake_decision <- df_djj_intake_complaints_clean %>% 
  mutate(intake_decision = as.numeric(intake_decision)) %>% 
  left_join(codebook_intake_decision_values,
            by = "intake_decision") %>% 
  ### create flags for (NOTE:THIS IS PRELIMINARY AND PENDING CONFIRMATION WITH DJJ RESEARCH STAFF)
  # intake decisions (petitioned, diverted, dismissed, other)
  # diversion (yes or no)
  # diversion outcome (successful, not successful and petitioned, not successful and not petitioned)
  # disposition outcomes (where intake complaint is petitioned)
  ### also create unique complaint-level ID
  mutate(intake_decision_clean = case_when(
    intake_decision_label%in%c("UNSUCCESSFUL DIVERSION/PETITION FILED", "SUCCESSFUL DIVERSION","UNSUCCESSFUL DIVERSION/NO PETITION FILED","REQ'D TO PARTICIPATE-DIVERSION") ~ "Diverted",
    intake_decision_label%in%c("REFERRED TO ANOTHER AGY FOR SV","UNOFFICIAL COUNSELING-FAMILY C") ~ "Diverted (Informal)",
    intake_decision_label%in%c("PETITION FILED", "PETITION/DETENTION ORDER FILED","COURT SUMMONS","PETITION/SHELTER CARE FILED") ~ "Petitioned",    
    intake_decision_label%in%c("RESOLVED", "COMPLAINT UNFOUNDED") ~ "Resolved/Dismissed",
    intake_decision_label%in%c("DETENTION ORDER ONLY","ACCEPTED VIA ICJ","RETURNED TO PROBATION SUPERVIS","PENDING","SHELTER CARE ONLY","RETURNED TO OUT-OF-STATE") ~ "Other",
   TRUE ~ as.character(NA)),
   intake_decision_clean = factor(intake_decision_clean,
                              levels = c("Petitioned","Diverted","Diverted (Informal)","Resolved/Dismissed","Other")),
   petition_court_summons_flag = ifelse(intake_decision_label=="COURT SUMMONS",
                                1,0),
   intake_diverted_flag = ifelse(intake_decision_label%in%c("UNSUCCESSFUL DIVERSION/PETITION FILED", "SUCCESSFUL DIVERSION","UNSUCCESSFUL DIVERSION/NO PETITION FILED","REQ'D TO PARTICIPATE-DIVERSION"),
                                1,0),
   intake_diverted_flag = factor(intake_diverted_flag,
                                levels = c(1,0),
                                labels = c("Yes","No")),
   diversion_successful_flag = ifelse(intake_decision_label%in%c("SUCCESSFUL DIVERSION"),
                                1,0),
   diversion_not_successful_petition_flag = ifelse(intake_decision_label%in%c("UNSUCCESSFUL DIVERSION/PETITION FILED"),
                                1,0),
   diversion_not_successful_no_petition_flag = ifelse(intake_decision_label%in%c("UNSUCCESSFUL DIVERSION/NO PETITION FILED"),
                                1,0),
   diversion_active_at_time_of_pull = ifelse(intake_decision_label=="REQ'D TO PARTICIPATE-DIVERSION",
                                                  1,0),
   intake_decision_regression_model_petition = case_when(
         intake_decision_label%in%c("PETITION FILED", "PETITION/DETENTION ORDER FILED","COURT SUMMONS","PETITION/SHELTER CARE FILED") ~ "Petitioned", 
    intake_decision_label%in%c("UNSUCCESSFUL DIVERSION/PETITION FILED", "SUCCESSFUL DIVERSION","UNSUCCESSFUL DIVERSION/NO PETITION FILED","REQ'D TO PARTICIPATE-DIVERSION","REFERRED TO ANOTHER AGY FOR SV","UNOFFICIAL COUNSELING-FAMILY C","RESOLVED") ~ "Not Petitioned",
   TRUE ~ as.character(NA)),
   intake_decision_regression_model_petition = factor(intake_decision_regression_model_petition,
                              levels = c("Petitioned","Not Petitioned")),
   unique_complaint_id = paste0(juvenile_number,case_number)) %>% 
  ### clean up petitioner type variable based on feedback from team
  mutate(referral_source_clean = case_when(
    petitioner_desc%in%c("BASE POLICE","Other Law Enforcment","POLICE DEPARTMENT","SHERIFF","STATE POLICE") ~ "Law Enforcement",
    petitioner_desc%in%c("SCHOOL OFFICIAL") ~ "School Official",
    petitioner_desc%in%c("School Res. Officer") ~ "School Resource Officer",    
    petitioner_desc%in%c("CITIZEN") ~ "Citizen",
    petitioner_desc%in%c("RELATIVE","SELF","SPOUSE") ~ "Relative/Spouse/Self",
    petitioner_desc%in%c("COURT") ~ "Court",
    petitioner_desc%in%c("PROBATION OFFICER") ~ "Probation Officer",
    petitioner_desc%in%c("ABC BOARD","COMMONWLTHS ATTORNEY","COMMUNITY SRV BOARD","DETENTION HOME","FIRE DEPARTMENT","GROUP HOME","MENTAL HLTH OFFICIAL","MERCHANTS","NCIS","SOCIAL SERVICE") ~ "Other",
   TRUE ~ as.character(NA))) %>% 
   ### clean up petitioner type variable for csu-level analysis (with fewer categories)
  mutate(referral_source_clean_csu_level_categories = case_when(
    petitioner_desc%in%c("BASE POLICE","Other Law Enforcment","POLICE DEPARTMENT","SHERIFF","STATE POLICE","PROBATION OFFICER") ~ "Law Enforcement",
    petitioner_desc%in%c("SCHOOL OFFICIAL","School Res. Officer") ~ "School",
    petitioner_desc%in%c("CITIZEN","RELATIVE","SELF","SPOUSE","COURT","ABC BOARD","COMMONWLTHS ATTORNEY","COMMUNITY SRV BOARD","DETENTION HOME","FIRE DEPARTMENT","GROUP HOME","MENTAL HLTH OFFICIAL","MERCHANTS","NCIS","SOCIAL SERVICE") ~ "Other",
   TRUE ~ as.character(NA))) %>% 
  ### create var for jj history using flags provided by DJJ
   mutate(jj_history_clean = case_when(
    (is.na(prior_adj)==TRUE) | (prior_other==0 & prior_chinsup==0 & prior_chins==0 & prior_other_status==0 & prior_misd==0 & prior_felony==0) ~ "No Prior JJ History",
    prior_other>0 ~ "Prior 'Other' History",
    (prior_chinsup>0 | prior_chins>0 | prior_other_status>0) ~ "Prior Status/CHINS/CHINsup",
    prior_misd>0 ~ "Prior Misdemeanor",
    prior_felony>0 ~ "Prior Felony",
    TRUE ~ as.character(NA)),
    jj_history_clean = factor(jj_history_clean,
                              levels = c("No Prior JJ History","Prior 'Other' History","Prior Status/CHINS/CHINsup","Prior Misdemeanor","Prior Felony"))) %>% 
  mutate(csu_region = case_when(
    csu %in% eastern_region ~ "Eastern",
    csu %in% northern_region ~ "Northern",
    csu %in% western_region ~ "Western",
    csu %in% southern_region ~ "Southern",
    csu %in% central_region ~ "Central", 
    TRUE ~ as.character(NA))) %>% 
  ### now create recidivism-type variable for research question b in part I analysis:
  ### for youth who are diverted, how likely are they to come back into the system with a new complaint or new petition within a year of the initial intake decision? we are treating a new case_number as a new complaint (as opposed to a violation of an existing complaint/case)
  ### our outcome variable will be re-complaint within a year of the initial intake decision date (0/1)
  ### since the file is already distinct by complaint/case,
  ### now arrange and group by individual to take the next complaint/intake date, if present
  ### following a complaint's intake date using dplyr::lead to take the next start date
  ### after a given end date (https://dplyr.tidyverse.org/reference/lead-lag.html)
  ### this will allow us to calculate the average time from one complaint intake date to the next
  ### for youth who don't have any subsequent complaints in the sample, there will be an
  ### NA for next_complaint_intake_date  
  
  ### first, create date var for petitioned cases only (for second outcome of interest -- petitioned within a year of initial complaint)
  mutate(date_opened_petitioned_only = ifelse(intake_decision_clean=="Petitioned",
                                              as.character(date_opened),
                                              NA),
           date_opened_petitioned_only = ymd(as.Date(as.character(date_opened_petitioned_only)))) %>% 
  arrange(juvenile_number,
          case_number,
          date_opened) %>%
  group_by(juvenile_number) %>%
  mutate(next_complaint_intake_date = dplyr::lead(date_opened,
                                                   1,
                                                   default=NA),
         next_petition_intake_date = dplyr::lead(date_opened_petitioned_only,
                                                   1,
                                                   default=NA)) %>%
  ungroup() %>%
  ### now calculate time between the two intake dates in days and flag records with a subsequent complaint within a year
  mutate(time_between_complaints = as.numeric(difftime(next_complaint_intake_date,
                                                                    date_opened,
                                                                    units="days")),
         time_between_complaints_within_one_year_flag = ifelse(time_between_complaints<=365 & !is.na(time_between_complaints)==TRUE,
                                                             1,0),
         regression_outcome_new_complaint_one_year_first_time_jj = ifelse(time_between_complaints_within_one_year_flag==1 & jj_history_clean=="No Prior JJ History",
                                                             1,0),
         time_between_complaint_petition = as.numeric(difftime(next_petition_intake_date,
                                                                    date_opened,
                                                                    units="days")),
         time_between_complaint_petition_within_one_year_flag = ifelse(time_between_complaint_petition<=365 & !is.na(time_between_complaint_petition)==TRUE,
                                                             1,0),
         regression_outcome_new_petition_one_year_first_time_jj = ifelse(time_between_complaint_petition_within_one_year_flag==1 & jj_history_clean=="No Prior JJ History",
                                                             1,0))


### double check creation of next_complaint_intake_date, time_between_complaints, and time_between_complaints_within_one_year_flag
codebook_intake_decision_values_timing_test <- df_complaints_youth_intake_decision %>% 
  # filter(jj_history_clean=="No Prior JJ History") %>% 
  dplyr::select(juvenile_number,
          case_number,
          intake_decision_clean,
          referral_source_clean,
          jj_history_clean,
          date_opened,
          next_complaint_intake_date,
          time_between_complaints,
          time_between_complaints_within_one_year_flag,
          regression_outcome_new_complaint_one_year_first_time_jj,
          regression_outcome_new_petition_one_year_first_time_jj) %>% 
  mutate(same_dates = ifelse(date_opened==next_complaint_intake_date,
                                                             1,0))



### this section is now outdated and no longer needed as we are joining all files together to create one analytic file

# #############################################
# ### clean and de-dup df_djj_intake_complaints_raw dataframe by youth
# ### this is our base youth-level demo file for the sample
# #############################################
# df_djj_youth_demo <- df_djj_intake_complaints_raw %>% 
#   distinct(juvenile_number,
#            .keep_all=TRUE) %>% 
#   ### clean race/ethnicity and gender
#   ### use factor function to assign labels to values
#   mutate(race_clean = case_when(
#     race=="I" & hispanic!="Y" ~ 1,
#     race=="A" & hispanic!="Y" ~ 2,
#     race=="B" & hispanic!="Y" ~ 3,
#     hispanic=="Y" ~ 4,
#     race=="W" & hispanic!="Y" ~ 5,
#     race %in% c("X","O") & hispanic!="Y" ~ 6,
#     TRUE ~ 7),
#     race_clean = factor(race_clean,
#          levels = c(1,2,3,4,5,6,7),
#          labels = c("American Indian",
#                     "Asian", 
#                     "Black", 
#                     "Hispanic", 
#                     "White", 
#                     "Other",
#                     "Missing"))) %>% 
#   mutate(gender_clean = case_when(
#     sex=="F" ~ 1,
#     sex=="M" ~ 2,
#     TRUE ~ as.numeric(NA)),
#     gender_clean = factor(gender_clean,
#          levels = c(1,2),
#          labels = c("Female", "Male"))) %>% 
#   ### temp cleaning of age -- pending feedback from DJJ
#   mutate(petition_age_clean = case_when(
#     pet_age < 12 ~ 1,
#     pet_age>= 12 &  pet_age< 14 ~ 2,
#     pet_age>= 14 &  pet_age< 16 ~ 3,
#     pet_age>= 16 &  pet_age< 20 ~ 4,
#     TRUE ~ as.numeric(NA)),
#     petition_age_clean = factor(petition_age_clean,
#          levels = c(1,2,3,4),
#          labels = c("Less than 12", 
#                     "12 to 13",
#                     "14 to 15",
#                     "16 to 20")),
#     intake_age_clean = case_when(
#     intake_age < 12 ~ 1,
#     intake_age>= 12 &  intake_age< 14 ~ 2,
#     intake_age>= 14 &  intake_age< 16 ~ 3,
#     intake_age>= 16 &  intake_age< 20 ~ 4,
#     TRUE ~ as.numeric(NA)),
#     intake_age_clean = factor(intake_age_clean,
#          levels = c(1,2,3,4),
#          labels = c("Less than 12", 
#                     "12 to 13",
#                     "14 to 15",
#                     "16 to 20"))) 

#############################################
### clean and de-dup df_djj_intake_complaints_raw dataframe for complaints that are petitioned
### we will use this file ensure we only keep disposition data for complaints/cases that are actually petitioned
### here are the intake decisions that I am considering as "petitioned" -- meaning they should have disposition data:
### "PETITION FILED", "PETITION/DETENTION ORDER FILED","COURT SUMMONS","PETITION/SHELTER CARE FILED","UNSUCCESSFUL DIVERSION/PETITION FILED"
#############################################
df_djj_intake_petitioned_only <- df_complaints_youth_intake_decision %>%
  filter(intake_decision_label%in%c("PETITION FILED", "PETITION/DETENTION ORDER FILED","COURT SUMMONS","PETITION/SHELTER CARE FILED","UNSUCCESSFUL DIVERSION/PETITION FILED")) %>% 
  distinct(juvenile_number,
           case_number) ### no records dropped

########################################
### clean and de-dup disposition dataframe
########################################
### note: disposition file is unique by youth, case number, offense number, disposition, and days from intake to disposition


### current hierarchy for de-duping disposition by severity:
# Commitment
# Detention
# Probation/Supervision
# Community Service
# Restitution
# Fine
# Other
# Deferral
# No further action/none

disposition_clean <- disposition %>% 
  ### remove records with missing disposition -- waiting on answer from DJJ on how to interpret this
  filter(!is.na(description)==TRUE) %>% 
  distinct(juvenile_number,
           case_number,
           offense_number,
           description,
           .keep_all=TRUE) %>% ### no records dropped
  ### create unique disposition ID for counts
  mutate(dispo_id = paste0(juvenile_number,
                           case_number,
                           offense_number,
                           description)) %>% 
  ### current options for grouping dispositions are: Detention, Commitment, Probation/Supervision, Deferral, Community Service, Fine, Treatment/Programming, No further action/none, Restitution, Other
  mutate(dispo_description_clean = case_when(
    description%in%c("COMMIT TO DJJ (16.1-278.8.14)","SERIOUS OFFENDER COMMITMENT TO DJJ (16.1-278.8.17) (16.1-285.1)") ~ 1,
    description%in%c("POST-DISPOSITIONAL DETENTION (16.1-278.8.16) (16.1-284.1)","SENTENCED TO DETENTION") ~ 2,
    description%in%c("COURT ORDER CONDITIONS AND LIMITATIONS (16.1-278.8.2)", "DEFER FINDING AND DISPOSITION W/PROBATION SUPERVISION (16.1-278.8.5)","PROBATION (16.1-278.8.7)","PROBATION AND COURT ORDERED ALCOHOL OR DRUG ABUSE TREATMENT (16.1-278.8.7a","(EXPIRED) DEFER DISPOSTION AND PLACE IN BOOT CAMP (16.1-278.8.4a)", "COURT ORDER GANG ACTIVITY PREVENTION PROGRAM (16.1-278.8.19)","FIRST OFFENSE DRUG VIOLATION, MANDATORY TREATMENT (16.1-278.8:01)","SUSPENDED COMMITMENT TO DJJ","SUSPENDED COMMITMENT TO DETENTION") ~ 3,
    description%in%c("COMMUNITY SERVICE (16.1-278.8.11)") ~ 4,
    description%in%c("RESTITUTION (16.1-278.8.10)") ~ 5,
    description%in%c("FINE NOT TO EXCEED $500 (16.1-278.8.8)") ~ 6,
    description%in%c("LOSS OF DRIVING PRIVS FOR ALCOHOL,FIREARM,OR TRUANCY(16.1-278.8.18)(16.1-278.9)","SENTENCED IN CIRCUIT COURT","SUSPEND DRIVER'S LICENSE/IMPOSE CURFEW (16.1-278.8.9)","TRAFFIC VIOLATION PENALTIES (16.1-278.8.12)","TRANSFER LEGAL CUSTODY (16.1-278.8.12)","UPHOLDING RULING OF THE LOWER COURT","(EXPIRED) TRANSFER TO CIRCUIT COURT","ADULT SENTENCED FOR JUVENILE OFFENSE (16.1-278.8.15) (16.1-284)","COURT ORDER NON-RESIDENTIAL PARENT PARTICIPATION IN PROGRAMS (16.1-278.8.6)","COURT ORDER PARENT PARTICIPATION IN PROGRAMS...FOR REHABILITATION (16.1-278.8.3)") ~ 7,
    description%in%c("DEFER DISPOSITION ON CONDITION OF GOOD BEHAVIOR") ~ 8,
    description%in%c("NO FURTHER ACTION") ~ 9,
   TRUE ~ as.numeric(NA))) %>% 
  ### use factor function to assign labels to values
  ### we'll use this to de-dup file and keep most severe disposition 
  mutate(dispo_description_clean = factor(dispo_description_clean,
         levels = c(1,2,3,4,5,6,7,8,9),
         labels = c("Commitment",
                    "Detention",
                    "Probation/Supervision",
                    "Community Service",
                    "Restitution",
                    "Fine",
                    "Other",
                    "Deferral",
                    "No further action/none"))) %>%
   ### create counts vars by disposition category before de-duping by case/complaint (keeping the most serious disposition)
  group_by(juvenile_number,
           case_number) %>% 
  mutate(count_commitment_dispo = n_distinct(dispo_id[dispo_description_clean=="Commitment"]),
         count_commitment_dispo = n_distinct(dispo_id[dispo_description_clean=="Detention"]),
         count_probation_supervision_dispo = n_distinct(dispo_id[dispo_description_clean=="Probation/Supervision"]),
         count_comm_service_dispo = n_distinct(dispo_id[dispo_description_clean=="Community Service"]),
         count_restitution_dispo = n_distinct(dispo_id[dispo_description_clean=="Restitution"]),
         count_fine_dispo = n_distinct(dispo_id[dispo_description_clean=="Fine"]),
         count_other_dispo = n_distinct(dispo_id[dispo_description_clean=="Other"]),
         count_deferral_dispo = n_distinct(dispo_id[dispo_description_clean=="Deferral"]),
         count_no_further_action_dispo = n_distinct(dispo_id[dispo_description_clean=="No further action/none"])) %>%
  ungroup() %>% 
  ### now order disposition by severity (by case_number)
  ### and keep record with most serious disposition based on above hierarchy
  arrange(juvenile_number,
          case_number,
          dispo_description_clean) %>% 
  distinct(juvenile_number,
           case_number,
           .keep_all = TRUE) %>% 
    ### temp cleaning of age -- pending feedback from DJJ
  mutate(dispo_age_clean = case_when(
    court_disp_age < 12 ~ 1,
    court_disp_age>= 12 &  court_disp_age< 14 ~ 2,
    court_disp_age>= 14 &  court_disp_age< 16 ~ 3,
    court_disp_age>= 16 &  court_disp_age< 20 ~ 4,
    TRUE ~ as.numeric(NA)),
    dispo_age_clean = factor(dispo_age_clean,
         levels = c(1,2,3,4),
         labels = c("Less than 12", 
                    "12 to 13",
                    "14 to 15",
                    "16 to 20"))) %>% 
  dplyr::rename(dispo_description = description) %>% 
  ### only keep disposition records with intake records/case IDs that were petitioned
  inner_join(df_djj_intake_petitioned_only,
             by = c("juvenile_number",
                    "case_number")) %>% 
  ### remove duplicated columns that we'll use from the intake complaints file
  dplyr::select(-offense_number)
  
```

```{r }
######################################################################################################
### join three files together to create preliminary analytic file for both part I and part II analysis
######################################################################################################

### first, left join df_complaints_youth_intake_decision and disposition_clean
### we have already dropped disposition records without accompanying intake records which were petitioned
### so any disposition missingness indicates that case wasn't petitioned

### also: because we have already de-duped both df_complaints_youth_intake_decision (keeping most serious offense per case/complaint) and disposition_clean (keeping most serious disposition per case/complaint), we can just join by case/complaint as opposed to charge
### this approach also covers the possibility that the most serious disposition is actually linked by DJJ to a less serious offense; we have separately pulled out the most serious offense and disposition without relying on a join across offense ID
df_analytic_complaints_disposition_caseload <- left_join(df_complaints_youth_intake_decision,
                                               disposition_clean,
                                               by = c("juvenile_number",
                                                      "case_number"))

# ### second, left join df_complaints_disposition_clean_1 and caseload_clean to create preliminary analytic file
# df_analytic_complaints_disposition_caseload <- left_join(df_complaints_disposition_clean_1,
#                                                          caseload_clean,
#                                                          by = c("juvenile_number",
#                                                                 "offense_number"))


```

```{r include=FALSE,message=FALSE,warning=FALSE}
### set sharepoint path using csgjcr function
sharepoint_ojjdp_va_analysis_analytic_data <- csgjcr::csg_sp_path(file.path("JJ_OJJDP/Data/VA/analysis/analytic"))

### write out df_analytic_complaints_disposition_caseload file for analysis (txt file for analysis in stata)
readr::write_delim(df_analytic_complaints_disposition_caseload,
          file.path(sharepoint_ojjdp_va_analysis_analytic_data,"df_analytic_complaints_disposition_caseload.txt"),
          delim = "|")

### write out df_analytic_complaints_disposition_caseload file for analysis
write_rds(df_analytic_complaints_disposition_caseload,
          file.path(sharepoint_ojjdp_va_analysis_analytic_data,"df_analytic_complaints_disposition_caseload.rds"))

# ### write out df_complaints_youth_intake_decision_csu file for analysis
# write_rds(df_complaints_youth_intake_decision_csu,
#           file.path(sharepoint_ojjdp_va_analysis_analytic_data,"df_complaints_youth_intake_decision_csu.rds"))

### write out caseload_clean file for analysis
write_rds(caseload_clean,
          file.path(sharepoint_ojjdp_va_analysis_analytic_data,"caseload_clean.rds"))

### write out disposition_clean file for analysis
write_rds(disposition_clean,
          file.path(sharepoint_ojjdp_va_analysis_analytic_data,"disposition_clean.rds"))

```

<br><br>
