---
title: "ojjdp_va_data_exploration_import_clean"
author: "Andrew Byrum"
format: html
---

**The purpose of this RMD is to import, join, and clean all data files provided by the Department of Juvenile Justice (DJJ) in Virginia -- provided to us as 2 excel file with 3 tabs of relational data as 3 tabs of data documentation**

```{r include=FALSE}
### call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap", "raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","ragg","tidylog","csgjcr")
```

```{r include=FALSE}
### pull in virginia djj data from raw data folder

### set sharepoint path using csgjcr function
sharepoint_ojjdp_va_raw_data <- csgjcr::csg_sp_path(file.path("JJ_OJJDP/Data/VA/raw"))

########################################################
### import first excel file w/ multiple tabs with purrr
########################################################

### using purrr::map, import list of tabs from excel worksheet
ojjdp_va_raw_tab_list_file_one <- purrr::map(purrr::set_names(excel_sheets(file.path(sharepoint_ojjdp_va_raw_data,
                                                              "CSG Front End data 01202023 - pt1 - SENSITIVE.xlsx"))),
                      read_excel, 
                      path = file.path(sharepoint_ojjdp_va_raw_data,"CSG Front End data 01202023 - pt1 - SENSITIVE.xlsx")) %>% 
  purrr::map(janitor::clean_names)

### clean names of all imported tabs before converting to dataframes
names(ojjdp_va_raw_tab_list_file_one) <- janitor::make_clean_names(names(ojjdp_va_raw_tab_list_file_one))

### then convert list of tabs to distinct dataframes with names from tabs
purrr::map(names(ojjdp_va_raw_tab_list_file_one),
           ~assign(.x, 
                   ojjdp_va_raw_tab_list_file_one[[.x]], 
        envir = .GlobalEnv)) 

########################################################
### now import second file from djj -- with only one tab
########################################################
df_djj_intake_complaints_raw <- openxlsx::read.xlsx(file.path(sharepoint_ojjdp_va_raw_data,
                                                              "CSG Front End data 01202023 - pt2 - SENSITIVE.xlsx"),
                                                    sheet = 1) %>% 
  clean_names()
```


